platform :ios, ‘7.0’

pod 'MJRefresh', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'

pod 'YTKNetwork', '~> 0.5.0'

pod 'Masonry', '~> 0.6.4'

pod 'YYKit', '~> 0.9.11'

pod 'pop', '~> 1.0.8'

pod 'LxDBAnything', '~> 1.1.0'

pod 'ReactiveCocoa', '2.5'

pod 'SDWebImage', '~>3.7'

#pod 'AMap3DMap' #3D地图SDK
pod 'AMap2DMap' #2D地图SDK(2D地图和3D地图不能同时使用)
pod 'AMapSearch' #搜索服务SDK
